import type { Metadata } from "next";
import { Anuphan } from "next/font/google";
import "@/styles/globals.css";

const anuphan = Anuphan({
	variable: "--font-anuphan",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next Gen | Thai PBS Project",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="th" className={`${anuphan.variable} antialiased`}>
			<body>{children}</body>
		</html>
	);
}
